# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Zero Delta
author: Deimos
email: 91100195+DeimosTheMisthios@users.noreply.github.com
description: >- # this means to ignore newlines until "baseurl:"
  This website contains my engineering and mathematics notes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://0δ.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: DeimosTheMisthios

# Build settings
theme: no-style-please
remote_theme: https://github.com/DeimosTheMisthios/no-style-please

theme_config:
  show_description: true
  date_format: "%Y-%b-%d"
  back_home_text: "←"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
