# Site settings
title: Zero Delta
author: Deimos
email: 91100195+DeimosTheMisthios@users.noreply.github.com
description: >-
  This website contains my engineering and mathematics notes.
baseurl: ""
url: "https://0δ.com"
github_username: DeimosTheMisthios

# Build settings
# theme: no-style-please
remote_theme: DeimosTheMisthios/no-style-please
theme_config:
  show_description: true
  date_format: "%Y-%b-%d"
  back_home_text: "←"
permalink: /:categories/:title/

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
